#!/bin/sh

STAGED_FILES_JS=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
STAGED_FILES_PY=$(git diff --cached --name-only --diff-filter=ACM | grep ".py$")

if [[ "$STAGED_FILES" == "" ]]; then
    exit 0
fi

PASS=true

echo "\nValidating Javascript:\n"
cd assets

for FILE in $STAGED_FILES; do
    npx eslint "$FILE"

    if [[ "$?" == 0 ]]; then
        echo "\t\033[32mESLint Passed: $FILE\033[0m"
    else
        echo "\t\033[41mESLint Failed: $FILE\033[0m"
        PASS=false
    fi
done

echo "\nJavascript validation completed!\n"

if ! $PASS; then
    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
    exit 1
fi

cd ..

echo "\nValidating Python:\n"

source venv/bin/activate

for FILE in $STAGED_FILES; do
    flake8 "$FILE"

    if [[ "$?" == 0 ]]; then
        echo "\t\033[32mFlake8 Passed: $FILE\033[0m"
    else
        echo "\t\033[41mFlake8 Failed: $FILE\033[0m"
        PASS=false
    fi
done

echo "\Python validation completed!\n"

if ! $PASS; then
    echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass Flake8 but do not. Please fix the Flake8 errors and try again.\n"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
