# Generated by Django 2.2.3 on 2019-07-29 15:47

from django.db import migrations


INITIAL_NAMES = ('person', 'place', 'food')


def add_initial(apps, _schema_registry):
    Category = apps.get_model('things', 'Category')
    initial = [Category(name=n, user=None) for n in INITIAL_NAMES]
    Category.objects.bulk_create(initial)


def remove_initial(apps, _schema_registry):
    Category = apps.get_model('things', 'Category')
    Category.objects.filter(name__in=INITIAL_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial, remove_initial)
    ]
