# Generated by Django 2.2.3 on 2019-08-06 20:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='metadata',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
