# Generated by Django 2.2.3 on 2019-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
